name: deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Run deploy script
      env:
        EC2_USER: ${{ secrets.EC2_USER }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      
      run: |
        echo "${SSH_PRIVATE_KEY}" > private_key.pem
        chmod 600 private_key.pem
        ssh -o ConnectTimeout=10 -i private_key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST '
          cd ~/CallumBot
          git pull
          cd ~
          ./stop.sh
          ./start.sh
          exit
          '
      shell: bash
